// Code generated by fluentfga. DO NOT EDIT.
package fga

import (
	sdkclient "github.com/openfga/go-sdk/client"
)

func NewAuthorizationModel(client sdkclient.SdkClient) AuthorizationModel {
	return AuthorizationModel{
		client: client,
	}
}

// AuthorizationModel represents the OpenFGA authorization model.
type AuthorizationModel struct {
	client sdkclient.SdkClient
}

// User provides access to the "user" type's relations.
func (m AuthorizationModel) User() UserType { return UserType{m.client} }

// Document provides access to the "document" type's relations.
func (m AuthorizationModel) Document() DocumentType { return DocumentType{m.client} }

// Domain provides access to the "domain" type's relations.
func (m AuthorizationModel) Domain() DomainType { return DomainType{m.client} }
