// Code generated by fluentfga. DO NOT EDIT.
package model

import (
	fluentfga "github.com/sectrean/fluentfga"
)

// DocumentCommenterRelation represents the "document#commenter" relation.
var DocumentCommenterRelation documentCommenterRelation

type documentCommenterRelation struct{}

func (documentCommenterRelation) FgaType() string     { return "document" }
func (documentCommenterRelation) Relation() string    { return "commenter" }
func (documentCommenterRelation) String() string      { return "document#commenter" }
func (documentCommenterRelation) ObjectType(Document) {}

func (r documentCommenterRelation) NewTuple(user DocumentCommenterUser, object Document) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}

// DocumentCommenterUser represents the direct user types for the "document#commenter" relation.
//
// It is a union of the following types:
//   - User
//   - DomainMemberUserset
type DocumentCommenterUser interface {
	fluentfga.Object
	documentCommenterUser()
}

func (User) documentCommenterUser()                {}
func (DomainMemberUserset) documentCommenterUser() {}

// DocumentOwnerRelation represents the "document#owner" relation.
var DocumentOwnerRelation documentOwnerRelation

type documentOwnerRelation struct{}

func (documentOwnerRelation) FgaType() string     { return "document" }
func (documentOwnerRelation) Relation() string    { return "owner" }
func (documentOwnerRelation) String() string      { return "document#owner" }
func (documentOwnerRelation) ObjectType(Document) {}

func (r documentOwnerRelation) NewTuple(user DocumentOwnerUser, object Document) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}

// DocumentOwnerUser represents the direct user types for the "document#owner" relation.
//
// It is a union of the following types:
//   - User
//   - DomainMemberUserset
type DocumentOwnerUser interface {
	fluentfga.Object
	documentOwnerUser()
}

func (User) documentOwnerUser()                {}
func (DomainMemberUserset) documentOwnerUser() {}

// DocumentParentRelation represents the "document#parent" relation.
var DocumentParentRelation documentParentRelation

type documentParentRelation struct{}

func (documentParentRelation) FgaType() string     { return "document" }
func (documentParentRelation) Relation() string    { return "parent" }
func (documentParentRelation) String() string      { return "document#parent" }
func (documentParentRelation) ObjectType(Document) {}

func (r documentParentRelation) NewTuple(user Document, object Document) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}

// DocumentViewerRelation represents the "document#viewer" relation.
var DocumentViewerRelation documentViewerRelation

type documentViewerRelation struct{}

func (documentViewerRelation) FgaType() string     { return "document" }
func (documentViewerRelation) Relation() string    { return "viewer" }
func (documentViewerRelation) String() string      { return "document#viewer" }
func (documentViewerRelation) ObjectType(Document) {}

func (r documentViewerRelation) NewTuple(user DocumentViewerUser, object Document) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}

// DocumentViewerUser represents the direct user types for the "document#viewer" relation.
//
// It is a union of the following types:
//   - User
//   - UserWildcard
//   - DomainMemberUserset
type DocumentViewerUser interface {
	fluentfga.Object
	documentViewerUser()
}

func (User) documentViewerUser()                {}
func (UserWildcard) documentViewerUser()        {}
func (DomainMemberUserset) documentViewerUser() {}

// DocumentWriterRelation represents the "document#writer" relation.
var DocumentWriterRelation documentWriterRelation

type documentWriterRelation struct{}

func (documentWriterRelation) FgaType() string     { return "document" }
func (documentWriterRelation) Relation() string    { return "writer" }
func (documentWriterRelation) String() string      { return "document#writer" }
func (documentWriterRelation) ObjectType(Document) {}

func (r documentWriterRelation) NewTuple(user DocumentWriterUser, object Document) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}

// DocumentWriterUser represents the direct user types for the "document#writer" relation.
//
// It is a union of the following types:
//   - User
//   - DomainMemberUserset
type DocumentWriterUser interface {
	fluentfga.Object
	documentWriterUser()
}

func (User) documentWriterUser()                {}
func (DomainMemberUserset) documentWriterUser() {}

// DomainMemberRelation represents the "domain#member" relation.
var DomainMemberRelation domainMemberRelation

type domainMemberRelation struct{}

func (domainMemberRelation) FgaType() string   { return "domain" }
func (domainMemberRelation) Relation() string  { return "member" }
func (domainMemberRelation) String() string    { return "domain#member" }
func (domainMemberRelation) ObjectType(Domain) {}

func (r domainMemberRelation) NewTuple(user User, object Domain) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}
