version: '3'

tasks:
  examples:
    cmds:
      - go run ./cmd/fluentfga generate ./examples/gdrive/model.fga ./examples/gdrive/
      - go run ./cmd/fluentfga generate ./examples/iot/model.fga ./examples/iot/
