// Code generated by fluentfga. DO NOT EDIT.
package fga

import (
	"fmt"
)

// User is the "user" type.
type User struct {
	UserID string
}

func (User) object() string   { return "user" }
func (u User) id() string     { return fmt.Sprint(u.UserID) }
func (u User) String() string { return fmt.Sprint("user:", u.UserID) }

type UserType struct {
	model *AuthorizationModel
}

// User Relations

// Document is the "document" type.
type Document struct {
	DocumentID string
}

func (Document) object() string   { return "document" }
func (d Document) id() string     { return fmt.Sprint(d.DocumentID) }
func (d Document) String() string { return fmt.Sprint("document:", d.DocumentID) }

type DocumentType struct {
	model *AuthorizationModel
}

// Document Relations

// Commenter is the "commenter" relation.
func (d DocumentType) Commenter() DirectRelation[User, Document] {
	return DirectRelation[User, Document]{
		model: d.model,
		rel:   "commenter",
		obj:   "document",
	}
}

// DocumentCommenterUserset is the userset for the "document#commenter" relation.
type DocumentCommenterUserset struct {
	Document
}

func (DocumentCommenterUserset) relation() string { return "commenter" }
func (c DocumentCommenterUserset) String() string {
	return fmt.Sprint(c.Document.String(), "#commenter")
}

func (d Document) Commenter() DocumentCommenterUserset {
	return DocumentCommenterUserset{d}
}

// Owner is the "owner" relation.
func (d DocumentType) Owner() DirectRelation[User, Document] {
	return DirectRelation[User, Document]{
		model: d.model,
		rel:   "owner",
		obj:   "document",
	}
}

// DocumentOwnerUserset is the userset for the "document#owner" relation.
type DocumentOwnerUserset struct {
	Document
}

func (DocumentOwnerUserset) relation() string { return "owner" }
func (o DocumentOwnerUserset) String() string { return fmt.Sprint(o.Document.String(), "#owner") }

func (d Document) Owner() DocumentOwnerUserset {
	return DocumentOwnerUserset{d}
}

// Viewer is the "viewer" relation.
func (d DocumentType) Viewer() DirectRelation[User, Document] {
	return DirectRelation[User, Document]{
		model: d.model,
		rel:   "viewer",
		obj:   "document",
	}
}

// DocumentViewerUserset is the userset for the "document#viewer" relation.
type DocumentViewerUserset struct {
	Document
}

func (DocumentViewerUserset) relation() string { return "viewer" }
func (v DocumentViewerUserset) String() string { return fmt.Sprint(v.Document.String(), "#viewer") }

func (d Document) Viewer() DocumentViewerUserset {
	return DocumentViewerUserset{d}
}

// Writer is the "writer" relation.
func (d DocumentType) Writer() DirectRelation[User, Document] {
	return DirectRelation[User, Document]{
		model: d.model,
		rel:   "writer",
		obj:   "document",
	}
}

// DocumentWriterUserset is the userset for the "document#writer" relation.
type DocumentWriterUserset struct {
	Document
}

func (DocumentWriterUserset) relation() string { return "writer" }
func (w DocumentWriterUserset) String() string { return fmt.Sprint(w.Document.String(), "#writer") }

func (d Document) Writer() DocumentWriterUserset {
	return DocumentWriterUserset{d}
}
