// Code generated by fluentfga. DO NOT EDIT.
package gdrive

import (
	fluentfga "github.com/sectrean/fluentfga"
)

// DocCommenterRelation represents the "document#commenter" relation.
type DocCommenterRelation struct{}

func (DocCommenterRelation) FgaType() string  { return "document" }
func (DocCommenterRelation) Relation() string { return "commenter" }
func (DocCommenterRelation) String() string   { return "document#commenter" }
func (DocCommenterRelation) ObjectType(Doc)   {}

func (r DocCommenterRelation) NewTuple(user DocCommenterUser, object Doc) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}

// DocCommenterUser represents the direct user types for the "document#commenter" relation.
//
// It is a union of the following types:
//   - User
//   - DomainMemberUserset
type DocCommenterUser interface {
	fluentfga.Object
	docCommenterUser()
}

func (User) docCommenterUser()                {}
func (DomainMemberUserset) docCommenterUser() {}

// DocOwnerRelation represents the "document#owner" relation.
type DocOwnerRelation struct{}

func (DocOwnerRelation) FgaType() string  { return "document" }
func (DocOwnerRelation) Relation() string { return "owner" }
func (DocOwnerRelation) String() string   { return "document#owner" }
func (DocOwnerRelation) ObjectType(Doc)   {}

func (r DocOwnerRelation) NewTuple(user DocOwnerUser, object Doc) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}

// DocOwnerUser represents the direct user types for the "document#owner" relation.
//
// It is a union of the following types:
//   - User
//   - DomainMemberUserset
type DocOwnerUser interface {
	fluentfga.Object
	docOwnerUser()
}

func (User) docOwnerUser()                {}
func (DomainMemberUserset) docOwnerUser() {}

// DocParentRelation represents the "document#parent" relation.
type DocParentRelation struct{}

func (DocParentRelation) FgaType() string  { return "document" }
func (DocParentRelation) Relation() string { return "parent" }
func (DocParentRelation) String() string   { return "document#parent" }
func (DocParentRelation) ObjectType(Doc)   {}

func (r DocParentRelation) NewTuple(user Doc, object Doc) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}

// DocViewerRelation represents the "document#viewer" relation.
type DocViewerRelation struct{}

func (DocViewerRelation) FgaType() string  { return "document" }
func (DocViewerRelation) Relation() string { return "viewer" }
func (DocViewerRelation) String() string   { return "document#viewer" }
func (DocViewerRelation) ObjectType(Doc)   {}

func (r DocViewerRelation) NewTuple(user DocViewerUser, object Doc) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}

// DocViewerUser represents the direct user types for the "document#viewer" relation.
//
// It is a union of the following types:
//   - User
//   - UserWildcard
//   - DomainMemberUserset
type DocViewerUser interface {
	fluentfga.Object
	docViewerUser()
}

func (User) docViewerUser()                {}
func (UserWildcard) docViewerUser()        {}
func (DomainMemberUserset) docViewerUser() {}

// DocWriterRelation represents the "document#writer" relation.
type DocWriterRelation struct{}

func (DocWriterRelation) FgaType() string  { return "document" }
func (DocWriterRelation) Relation() string { return "writer" }
func (DocWriterRelation) String() string   { return "document#writer" }
func (DocWriterRelation) ObjectType(Doc)   {}

func (r DocWriterRelation) NewTuple(user DocWriterUser, object Doc) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}

// DocWriterUser represents the direct user types for the "document#writer" relation.
//
// It is a union of the following types:
//   - User
//   - DomainMemberUserset
type DocWriterUser interface {
	fluentfga.Object
	docWriterUser()
}

func (User) docWriterUser()                {}
func (DomainMemberUserset) docWriterUser() {}

// DomainMemberRelation represents the "domain#member" relation.
type DomainMemberRelation struct{}

func (DomainMemberRelation) FgaType() string   { return "domain" }
func (DomainMemberRelation) Relation() string  { return "member" }
func (DomainMemberRelation) String() string    { return "domain#member" }
func (DomainMemberRelation) ObjectType(Domain) {}

func (r DomainMemberRelation) NewTuple(user User, object Domain) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}
