// Code generated by fluentfga. DO NOT EDIT.
package gdrive

import (
	fluentfga "github.com/sectrean/fluentfga"
)

// DocCommenterRelation represents the "document#commenter" relation.
var DocCommenterRelation docCommenterRelation

type docCommenterRelation struct{}

func (docCommenterRelation) FgaType() string  { return "document" }
func (docCommenterRelation) Relation() string { return "commenter" }
func (docCommenterRelation) String() string   { return "document#commenter" }
func (docCommenterRelation) ObjectType(Doc)   {}

func (r docCommenterRelation) NewTuple(user DocCommenterUser, object Doc) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}

// DocCommenterUser represents the direct user types for the "document#commenter" relation.
//
// It is a union of the following types:
//   - User
//   - DomainMemberUserset
type DocCommenterUser interface {
	fluentfga.Object
	docCommenterUser()
}

func (User) docCommenterUser()                {}
func (DomainMemberUserset) docCommenterUser() {}

// DocOwnerRelation represents the "document#owner" relation.
var DocOwnerRelation docOwnerRelation

type docOwnerRelation struct{}

func (docOwnerRelation) FgaType() string  { return "document" }
func (docOwnerRelation) Relation() string { return "owner" }
func (docOwnerRelation) String() string   { return "document#owner" }
func (docOwnerRelation) ObjectType(Doc)   {}

func (r docOwnerRelation) NewTuple(user DocOwnerUser, object Doc) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}

// DocOwnerUser represents the direct user types for the "document#owner" relation.
//
// It is a union of the following types:
//   - User
//   - DomainMemberUserset
type DocOwnerUser interface {
	fluentfga.Object
	docOwnerUser()
}

func (User) docOwnerUser()                {}
func (DomainMemberUserset) docOwnerUser() {}

// DocParentRelation represents the "document#parent" relation.
var DocParentRelation docParentRelation

type docParentRelation struct{}

func (docParentRelation) FgaType() string  { return "document" }
func (docParentRelation) Relation() string { return "parent" }
func (docParentRelation) String() string   { return "document#parent" }
func (docParentRelation) ObjectType(Doc)   {}

func (r docParentRelation) NewTuple(user Doc, object Doc) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}

// DocViewerRelation represents the "document#viewer" relation.
var DocViewerRelation docViewerRelation

type docViewerRelation struct{}

func (docViewerRelation) FgaType() string  { return "document" }
func (docViewerRelation) Relation() string { return "viewer" }
func (docViewerRelation) String() string   { return "document#viewer" }
func (docViewerRelation) ObjectType(Doc)   {}

func (r docViewerRelation) NewTuple(user DocViewerUser, object Doc) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}

// DocViewerUser represents the direct user types for the "document#viewer" relation.
//
// It is a union of the following types:
//   - User
//   - UserWildcard
//   - DomainMemberUserset
type DocViewerUser interface {
	fluentfga.Object
	docViewerUser()
}

func (User) docViewerUser()                {}
func (UserWildcard) docViewerUser()        {}
func (DomainMemberUserset) docViewerUser() {}

// DocWriterRelation represents the "document#writer" relation.
var DocWriterRelation docWriterRelation

type docWriterRelation struct{}

func (docWriterRelation) FgaType() string  { return "document" }
func (docWriterRelation) Relation() string { return "writer" }
func (docWriterRelation) String() string   { return "document#writer" }
func (docWriterRelation) ObjectType(Doc)   {}

func (r docWriterRelation) NewTuple(user DocWriterUser, object Doc) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}

// DocWriterUser represents the direct user types for the "document#writer" relation.
//
// It is a union of the following types:
//   - User
//   - DomainMemberUserset
type DocWriterUser interface {
	fluentfga.Object
	docWriterUser()
}

func (User) docWriterUser()                {}
func (DomainMemberUserset) docWriterUser() {}

// DomainMemberRelation represents the "domain#member" relation.
var DomainMemberRelation domainMemberRelation

type domainMemberRelation struct{}

func (domainMemberRelation) FgaType() string   { return "domain" }
func (domainMemberRelation) Relation() string  { return "member" }
func (domainMemberRelation) String() string    { return "domain#member" }
func (domainMemberRelation) ObjectType(Domain) {}

func (r domainMemberRelation) NewTuple(user User, object Domain) fluentfga.Tuple {
	return fluentfga.NewTuple(user, r, object)
}
