// Code generated by fluentfga. DO NOT EDIT.
package gdrive

import (
	"fmt"

	fluentfga "github.com/sectrean/fluentfga"
)

// User represents an object of the "user" type.
type User struct {
	ID string
}

func (User) Provider() fluentfga.ObjectProvider { return objectProvider{} }
func (User) FgaType() string                    { return "user" }
func (o User) Identifier() string               { return fmt.Sprint(o.ID) }
func (o User) String() string                   { return fmt.Sprint("user:", o.ID) }
func (User) IsFilterable()                      {}

func newUserObject(id string) (User, error) {
	o := User{}
	_, err := fmt.Sscan(id, &o.ID)

	return o, err
}

// UserWildcard represents the "user:*" wildcard.
type UserWildcard struct{}

func (UserWildcard) Provider() fluentfga.ObjectProvider { return objectProvider{} }
func (UserWildcard) FgaType() string                    { return "user" }
func (UserWildcard) Identifier() string                 { return "*" }
func (UserWildcard) String() string                     { return "user:*" }
func (UserWildcard) IsWildcard()                        {}

// Doc represents an object of the "document" type.
type Doc struct {
	DocID string

	// Direct Relations

	Commenter DocCommenterUser `fga:"commenter"`
	Owner     DocOwnerUser     `fga:"owner"`
	Parent    *Doc             `fga:"parent"`
	Viewer    DocViewerUser    `fga:"viewer"`
	Writer    DocWriterUser    `fga:"writer"`
}

func (Doc) Provider() fluentfga.ObjectProvider { return objectProvider{} }
func (Doc) FgaType() string                    { return "document" }
func (o Doc) Identifier() string               { return fmt.Sprint(o.DocID) }
func (o Doc) String() string                   { return fmt.Sprint("document:", o.DocID) }
func (Doc) IsFilterable()                      {}

func newDocObject(id string) (Doc, error) {
	o := Doc{}
	_, err := fmt.Sscan(id, &o.DocID)

	return o, err
}

// Domain represents an object of the "domain" type.
type Domain struct {
	DomainID int64

	// Direct Relations

	Member *User `fga:"member"`
}

func (Domain) Provider() fluentfga.ObjectProvider { return objectProvider{} }
func (Domain) FgaType() string                    { return "domain" }
func (o Domain) Identifier() string               { return fmt.Sprint(o.DomainID) }
func (o Domain) String() string                   { return fmt.Sprint("domain:", o.DomainID) }
func (Domain) IsFilterable()                      {}

func newDomainObject(id string) (Domain, error) {
	o := Domain{}
	_, err := fmt.Sscan(id, &o.DomainID)

	return o, err
}

// DomainMemberUserset represents the "domain:{DomainID}#member" userset.
type DomainMemberUserset struct {
	Domain
}

func (DomainMemberUserset) Provider() fluentfga.ObjectProvider { return objectProvider{} }
func (DomainMemberUserset) Relation() string                   { return "member" }
func (u DomainMemberUserset) String() string                   { return fmt.Sprint("domain:", u.Identifier(), "#member") }
func (DomainMemberUserset) IsUserset()                         {}
func (DomainMemberUserset) IsFilterable()                      {}

type objectProvider struct{}

func (objectProvider) NewObject(typ, id, rel string) (fluentfga.Object, error) {
	switch {
	case typ == "user" && id == "*" && rel == "":
		return UserWildcard{}, nil
	case typ == "user" && rel == "":
		return newUserObject(id)
	case typ == "document" && rel == "":
		return newDocObject(id)
	case typ == "domain" && rel == "member":
		obj, err := newDomainObject(id)
		return DomainMemberUserset{obj}, err
	case typ == "domain" && rel == "":
		return newDomainObject(id)

	default:
		// TODO: Custom error type
		return nil, fmt.Errorf("unknown object type %s %s %s", typ, id, rel)
	}
}
