// Code generated by fluentfga. DO NOT EDIT.
package fga

import (
	sdkclient "github.com/openfga/go-sdk/client"
)

type Type interface {
	typeName() string
}

// UserType represents the "user" type and provides interfaces for its relations.
type UserType struct {
	client sdkclient.SdkClient
}

func (UserType) typeName() string { return "user" }

// DeviceType represents the "device" type and provides interfaces for its relations.
type DeviceType struct {
	client sdkclient.SdkClient
}

func (DeviceType) typeName() string { return "device" }

// DeviceRenamer provides an interface for the "device#device_renamer" relation.
func (d DeviceType) DeviceRenamer() IndirectRelation[Device] {
	return IndirectRelation[Device]{
		client: d.client,
		typ:    "device",
		rel:    "device_renamer",
	}
}

// ItAdmin provides an interface for the "device#it_admin" relation.
func (d DeviceType) ItAdmin() DirectRelation[DeviceItAdminUser, Device] {
	return DirectRelation[DeviceItAdminUser, Device]{IndirectRelation[Device]{
		client: d.client,
		typ:    "device",
		rel:    "it_admin",
	}}
}

// DeviceItAdminUser represents the possible user types for the "device#it_admin" relation.
// It is a union of the following types:
//   - User
//   - DeviceGroupItAdminUserset
type DeviceItAdminUser interface {
	Object
	deviceItAdminUser()
}

func (User) deviceItAdminUser()                      {}
func (DeviceGroupItAdminUserset) deviceItAdminUser() {}

// LiveVideoViewer provides an interface for the "device#live_video_viewer" relation.
func (d DeviceType) LiveVideoViewer() IndirectRelation[Device] {
	return IndirectRelation[Device]{
		client: d.client,
		typ:    "device",
		rel:    "live_video_viewer",
	}
}

// RecordedVideoViewer provides an interface for the "device#recorded_video_viewer" relation.
func (d DeviceType) RecordedVideoViewer() IndirectRelation[Device] {
	return IndirectRelation[Device]{
		client: d.client,
		typ:    "device",
		rel:    "recorded_video_viewer",
	}
}

// SecurityGuard provides an interface for the "device#security_guard" relation.
func (d DeviceType) SecurityGuard() DirectRelation[DeviceSecurityGuardUser, Device] {
	return DirectRelation[DeviceSecurityGuardUser, Device]{IndirectRelation[Device]{
		client: d.client,
		typ:    "device",
		rel:    "security_guard",
	}}
}

// DeviceSecurityGuardUser represents the possible user types for the "device#security_guard" relation.
// It is a union of the following types:
//   - User
//   - DeviceGroupSecurityGuardUserset
type DeviceSecurityGuardUser interface {
	Object
	deviceSecurityGuardUser()
}

func (User) deviceSecurityGuardUser()                            {}
func (DeviceGroupSecurityGuardUserset) deviceSecurityGuardUser() {}

// DeviceGroupType represents the "device_group" type and provides interfaces for its relations.
type DeviceGroupType struct {
	client sdkclient.SdkClient
}

func (DeviceGroupType) typeName() string { return "device_group" }

// ItAdmin provides an interface for the "device_group#it_admin" relation.
func (d DeviceGroupType) ItAdmin() DirectRelation[User, DeviceGroup] {
	return DirectRelation[User, DeviceGroup]{IndirectRelation[DeviceGroup]{
		client: d.client,
		typ:    "device_group",
		rel:    "it_admin",
	}}
}

// SecurityGuard provides an interface for the "device_group#security_guard" relation.
func (d DeviceGroupType) SecurityGuard() DirectRelation[User, DeviceGroup] {
	return DirectRelation[User, DeviceGroup]{IndirectRelation[DeviceGroup]{
		client: d.client,
		typ:    "device_group",
		rel:    "security_guard",
	}}
}
