// Code generated by fluentfga. DO NOT EDIT.
package fga

import (
	"fmt"
	"strings"

	sdk "github.com/openfga/go-sdk"
)

type Object interface {
	typeName() string
	id() string
	String() string
}

type Userset interface {
	Object
	Relation
}

// User represents an object of the "user" type.
type User struct {
	UserID string
}

func (User) typeName() string { return "user" }
func (u User) id() string     { return fmt.Sprint(u.UserID) }
func (u User) String() string { return fmt.Sprint("user:", u.UserID) }

// Device represents an object of the "device" type.
type Device struct {
	DeviceID string
}

func (Device) typeName() string { return "device" }
func (d Device) id() string     { return fmt.Sprint(d.DeviceID) }
func (d Device) String() string { return fmt.Sprint("device:", d.DeviceID) }

// DeviceGroup represents an object of the "device_group" type.
type DeviceGroup struct {
	DeviceGroupID string
}

func (DeviceGroup) typeName() string { return "device_group" }
func (d DeviceGroup) id() string     { return fmt.Sprint(d.DeviceGroupID) }
func (d DeviceGroup) String() string { return fmt.Sprint("device_group:", d.DeviceGroupID) }

// DeviceGroupItAdminUserset is the "device_group:{DeviceGroupID}#it_admin" userset.
type DeviceGroupItAdminUserset struct {
	DeviceGroup
}

func (DeviceGroupItAdminUserset) relation() string { return "it_admin" }
func (u DeviceGroupItAdminUserset) String() string {
	return fmt.Sprint("device_group:", u.id(), "#it_admin")
}

// DeviceGroupUserset returns the "device_group:{DeviceGroupID}#it_admin" userset.
func (d DeviceGroup) ItAdminUserset() DeviceGroupItAdminUserset {
	return DeviceGroupItAdminUserset{d}
}

// DeviceGroupSecurityGuardUserset is the "device_group:{DeviceGroupID}#security_guard" userset.
type DeviceGroupSecurityGuardUserset struct {
	DeviceGroup
}

func (DeviceGroupSecurityGuardUserset) relation() string { return "security_guard" }
func (u DeviceGroupSecurityGuardUserset) String() string {
	return fmt.Sprint("device_group:", u.id(), "#security_guard")
}

// DeviceGroupUserset returns the "device_group:{DeviceGroupID}#security_guard" userset.
func (d DeviceGroup) SecurityGuardUserset() DeviceGroupSecurityGuardUserset {
	return DeviceGroupSecurityGuardUserset{d}
}

func newObjects[O Object](objs []string) ([]O, error) {
	objects := make([]O, len(objs))

	// TODO: Use multierror to collect all errors.
	for i, s := range objs {
		parts := strings.Split(s, ":")
		if len(parts) != 2 {
			return nil, fmt.Errorf("invalid object: %q", s)
		}

		obj := newObject(parts[0], parts[1])
		o, ok := obj.(O)
		if !ok {
			return nil, fmt.Errorf("unexpected object type: %q", s)
		}

		objects[i] = o
	}
	return objects, nil
}

func newObject(typ, id string) Object {
	switch typ {
	case "user":
		return User{UserID: id}
	case "device":
		return Device{DeviceID: id}
	case "device_group":
		return DeviceGroup{DeviceGroupID: id}

	default:
		return unknownObject{typ, id}
	}
}

func newUsers(data []sdk.User) []Object {
	users := make([]Object, len(data))

	for i, u := range data {
		users[i] = newUser(u)
	}
	return users
}

func newUser(u sdk.User) Object {
	if u.Object != nil {
		return newObject(u.Object.Type, u.Object.Id)
	}
	if u.Userset != nil {
		return newUserset(u.Userset.Type, u.Userset.Id, u.Userset.Relation)
	}
	if u.Wildcard != nil {
		return newObject(u.Wildcard.Type, "*")
	}

	panic("unknown user type")
}

func newUserset(typ, id, rel string) Userset {
	if typ == "device_group" && rel == "it_admin" {
		return DeviceGroupItAdminUserset{DeviceGroup{DeviceGroupID: id}}
	}
	if typ == "device_group" && rel == "security_guard" {
		return DeviceGroupSecurityGuardUserset{DeviceGroup{DeviceGroupID: id}}
	}

	panic("unknown userset type")
}

// unknownObject represents an object of an unknown type.
//
// If the authorization model version used by OpenFGA is different from the one this code was generated for,
// it's possible that the server will return objects that are not known to this code.
type unknownObject struct {
	objType, objID string
}

func (o unknownObject) typeName() string { return o.objType }
func (o unknownObject) id() string       { return o.objID }
func (o unknownObject) String() string   { return fmt.Sprint(o.objType, ":", o.objID) }
