// Code generated by fluentfga. DO NOT EDIT.
package fga

import (
	"errors"
	"fmt"
	"strings"

	sdk "github.com/openfga/go-sdk"
)

// Object represents an entity in the system.
//
// An object is a combination of a type and an identifier.
//
// For example:
// - workspace:fb83c013-3060-41f4-9590-d3233a67938f
// - repository:auth0/express-jwt
// - organization:org_ajUc9kJ
// - document:new-roadmap
type Object interface {
	typeName() string
	identifier() string
	String() string
}

type Userset interface {
	Object
	Relation
}

type ContextualTuple interface {
	tupleKey() sdk.TupleKey
}

// UserObject represents an object of the "user" type.
type UserObject struct {
	UserID string
}

func (UserObject) typeName() string     { return "user" }
func (o UserObject) identifier() string { return fmt.Sprint(o.UserID) }
func (o UserObject) String() string     { return fmt.Sprint("user:", o.UserID) }

// DeviceObject represents an object of the "device" type.
type DeviceObject struct {
	DeviceID string
}

func (DeviceObject) typeName() string     { return "device" }
func (o DeviceObject) identifier() string { return fmt.Sprint(o.DeviceID) }
func (o DeviceObject) String() string     { return fmt.Sprint("device:", o.DeviceID) }

// DeviceGroupObject represents an object of the "device_group" type.
type DeviceGroupObject struct {
	DeviceGroupID string
}

func (DeviceGroupObject) typeName() string     { return "device_group" }
func (o DeviceGroupObject) identifier() string { return fmt.Sprint(o.DeviceGroupID) }
func (o DeviceGroupObject) String() string     { return fmt.Sprint("device_group:", o.DeviceGroupID) }

// DeviceGroupItAdminUserset is the "device_group:{DeviceGroupID}#it_admin" userset.
type DeviceGroupItAdminUserset struct {
	DeviceGroupObject
}

func (DeviceGroupItAdminUserset) relation() string { return "it_admin" }
func (u DeviceGroupItAdminUserset) String() string {
	return fmt.Sprint("device_group:", u.identifier(), "#it_admin")
}

// DeviceGroupUserset returns the "device_group:{DeviceGroupID}#it_admin" userset.
func (o DeviceGroupObject) ItAdminUserset() DeviceGroupItAdminUserset {
	return DeviceGroupItAdminUserset{o}
}

// DeviceGroupSecurityGuardUserset is the "device_group:{DeviceGroupID}#security_guard" userset.
type DeviceGroupSecurityGuardUserset struct {
	DeviceGroupObject
}

func (DeviceGroupSecurityGuardUserset) relation() string { return "security_guard" }
func (u DeviceGroupSecurityGuardUserset) String() string {
	return fmt.Sprint("device_group:", u.identifier(), "#security_guard")
}

// DeviceGroupUserset returns the "device_group:{DeviceGroupID}#security_guard" userset.
func (o DeviceGroupObject) SecurityGuardUserset() DeviceGroupSecurityGuardUserset {
	return DeviceGroupSecurityGuardUserset{o}
}

func parseObject[O Object](s string) (o O, _ error) {
	parts := strings.Split(s, ":")
	if len(parts) != 2 {
		return o, fmt.Errorf("invalid object: %q", s)
	}

	object := newObject(parts[0], parts[1])

	o, ok := object.(O)
	if !ok {
		return o, fmt.Errorf(
			"unexpected object type: %T does not implement %T: object %q",
			object, o, s,
		)
	}

	return o, nil
}

func newObjects[O Object](objs []string) ([]O, error) {
	objects := make([]O, 0, len(objs))
	var errs []error

	for _, s := range objs {
		obj, err := parseObject[O](s)
		if err != nil {
			errs = append(errs, err)
			continue
		}

		objects = append(objects, obj)
	}

	return objects, errors.Join(errs...)
}

func newObject(typ, id string) Object {
	switch {
	case typ == "user":
		return UserObject{UserID: id}
	case typ == "device":
		return DeviceObject{DeviceID: id}
	case typ == "device_group":
		return DeviceGroupObject{DeviceGroupID: id}

	default:
		return unknownObject{typ, id}
	}
}

func newUsers(data []sdk.User) ([]Object, error) {
	users := make([]Object, 0, len(data))
	var errs []error

	for _, u := range data {
		user, err := newUser(u)
		if err != nil {
			errs = append(errs, err)
			continue
		}

		users = append(users, user)
	}

	return users, errors.Join(errs...)
}

func newUser(u sdk.User) (Object, error) {
	if u.Object != nil {
		return newObject(u.Object.Type, u.Object.Id), nil
	}
	if u.Wildcard != nil {
		return newObject(u.Wildcard.Type, "*"), nil
	}
	if u.Userset != nil {
		return newUserset(u.Userset.Type, u.Userset.Id, u.Userset.Relation), nil
	}

	return nil, fmt.Errorf("unknown user type %v", u)
}

func newUserset(typ, id, rel string) Userset {
	if typ == "device_group" && rel == "it_admin" {
		return DeviceGroupItAdminUserset{DeviceGroupObject{DeviceGroupID: id}}
	}
	if typ == "device_group" && rel == "security_guard" {
		return DeviceGroupSecurityGuardUserset{DeviceGroupObject{DeviceGroupID: id}}
	}

	return unknownUserset{typ, id, rel}
}

// unknownObject represents an object of an unknown type.
//
// If the authorization model version used by OpenFGA is different from the one this code was generated for,
// it's possible that the server will return objects that are not known to this code.
type unknownObject struct {
	typ, id string
}

func (o unknownObject) typeName() string   { return o.typ }
func (o unknownObject) identifier() string { return o.id }
func (o unknownObject) String() string     { return fmt.Sprint(o.typ, ":", o.id) }

type unknownUserset struct {
	typ, id, rel string
}

func (u unknownUserset) typeName() string   { return u.typ }
func (u unknownUserset) identifier() string { return u.id }
func (u unknownUserset) relation() string   { return u.rel }
func (u unknownUserset) String() string     { return fmt.Sprint(u.typ, ":", u.id, '#', u.rel) }
