// Code generated by fluentfga. DO NOT EDIT.
package fga

import (
	sdkclient "github.com/openfga/go-sdk/client"
)

func NewAuthorizationModel(client sdkclient.SdkClient) AuthorizationModel {
	return AuthorizationModel{
		client: client,
	}
}

// AuthorizationModel represents the OpenFGA authorization model.
type AuthorizationModel struct {
	client sdkclient.SdkClient
}

// User provides access to the "user" type's relations.
func (m AuthorizationModel) User() UserType { return UserType{m.client} }

// Device provides access to the "device" type's relations.
func (m AuthorizationModel) Device() DeviceType { return DeviceType{m.client} }

// DeviceGroup provides access to the "device_group" type's relations.
func (m AuthorizationModel) DeviceGroup() DeviceGroupType { return DeviceGroupType{m.client} }
